name: ShellCheck

on:
  push:
    paths:
      - "**.sh"
      - ".github/workflows/shellcheck.yml"
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        working-directory: ${{ github.workspace }}
        run: |
          (cd src && shellcheck -x cleanup.sh)
          shellcheck src/lib/*.sh
          shellcheck tests/*.sh

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          chmod +x tests/*.sh
          for test in tests/test_*.sh; do
            echo "Running $test"
            "$test"
          done

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          chmod +x src/cleanup.sh
          chmod +x src/lib/*.sh
          mkdir -p ~/.local/share/jupyter/runtime
          mkdir -p ~/.local/state/jupyter-cleanup
          touch ~/.local/share/jupyter/runtime/test.json
          chmod 755 ~/.local/share/jupyter/runtime
          chmod 644 ~/.local/share/jupyter/runtime/test.json

      - name: Run cleanup script
        run: |
          cd src
          export DEBUG=1
          ./cleanup.sh || {
            echo "Script failed, checking logs:"
            cat ~/.local/state/jupyter-cleanup/cleanup-*.log
            echo "Environment info:"
            env | grep -i jupyter || true
            ls -la ~/.local/share/jupyter/runtime || true
            exit 1
          }

      - name: Verify cleanup
        run: |
          if [[ -f ~/.local/share/jupyter/runtime/test.json ]]; then
            echo "ERROR: Test file still exists"
            ls -la ~/.local/share/jupyter/runtime/
            exit 1
          fi
          echo "Cleanup successful"
